server:
  port: 8081

rocketmq:
  name-server: 192.168.39.233:9876
  producer:
    group: "default-producer-dq-group"
    retry-times-when-send-failed: 3
  consumer:
    group: "default-consumer-dq-group"
    pull-batch-size: 20
  topics:
    common-topic: "dq-topic"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.39.233:13306/rocket_mq_springboot?serverTimezone=Asia/Shanghai
    username: root
    password: test123
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null